version: '2'

services:
  app:
    image: 'antoniosk/gestor_peixaria:latest'
    container_name: gestor
    depends_on:
      - db
    links:
      - db
    environment:
      - MAIL_PROFILE_SENDER=sendgrid
      - SERVER_PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=gestor_peixaria
      - SENDGRID_API_KEY=api_key
      - SENDGRID_FROM_EMAIL=from_email
      - SENDGRID_FROM_NAME=from_name
      - MAILGUN_API_USERNAME=api_username
      - MAILGUN_API_PASSWORD=api_key
      - MAILGUN_BASE_URL=base_url
      - MAILGUN_MESSAGES_URL=messages_url
      - MAIL_HOST=smtp-mail.outlook.com
      - MAIL_PORT=587
      - MAIL_PROTOCOL=smtp
      - MAIL_USERNAME=username
      - MAIL_PASSWORD=password
      - UUID_JWT_SECRET=secret
      - JWT_EXPIRATION_TIME=3600
      - JWT_REFRESH_TIME=3600
      - GENERATE_KEY=senha
      - URL_CORS=http://localhost:4200
  db:
    image: 'postgres:14.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gestor_peixaria