spring:
  datasource:
    url: ${DATABASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  sendgrid:
    api-key: ${SENDGRID_API_KEY}

personal:
  mail:
    fromMail: ${SENDGRID_FROM_MAIL}
    fromName: ${SENDGRID_FROM_NAME}
  security:
    jwtSecret: ${JWT_SECRET}
    url-cors: ${URL_CORS}

mailgun:
  api:
    username: ${MAILGUN_USERNAME}
    password: ${MAILGUN_PASSWORD}
    base:
      url: ${MAILGUN_API_BASE_URL}
    messages:
      url: ${MAILGUN_MESSAGES_URL}