spring:
  application:
    name: gestor-peixaria
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    activate:
      on-profile: dev