spring:
  application:
    name: gestor_peixaria
  datasource:
    url: jdbc:postgresql://localhost:5432/gestor_peixaria
    username: postgres
    password: postgres
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  sendgrid:
    api-key: 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
logging:
  level:
    org.hibernate.SQL: DEBUG
    web: debug
personal:
  mail:
    fromMail: antonio.sgarbi@hotmail.com
    fromName: Fish Stock

mailgun:
  api:
    username: api
    password: d1674f346083ed435ac44e64a1944d3c-1b8ced53-7999ca56
    base:
      url: https://api.mailgun.net/v3/sandboxb0912365106e427e9fd0d5eacaf11823.mailgun.org
    messages:
      url: https://api.mailgun.net/v3/sandboxb0912365106e427e9fd0d5eacaf11823.mailgun.org/messages