spring:
  mvc:
    throw-exception-if-no-handler-found: true
  sendgrid:
    api-key: api-key
  web:
    resources:
      add-mappings: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    web: debug

personal:
  mail:
    fromMail: antonio.sgarbi@hotmail.com
    fromName: Fish Stock
