spring:
  application:
    name: gestor-peixaria
  datasource:
    url: jdbc:postgresql://localhost:5432/gestor_peixaria
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: @active.profile@ #actions
#    active: dev
#    active: test
#    active: smtp
#    active: mailgun
#    active: heroku

personal:
  security:
    jwtSecret: aa713c1f-8025-4ce4-bfe8-0a8ea6110eea
    jwtExpirationMs: 360 000 000
    jwtRefreshExpirationMs: 6 000 000
    passwordGenerate: generated
    url-cors: http://localhost:4200
