spring:
  application:
    name: gestor-peixaria
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  profiles:
#    active: @active.profile@ #actions
#    active: dev
    active: heroku
  mail:
    host: smtp-mail.outlook.com #gmail smtp.gmail.com
    port: 587
    protocol: smtp
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
personal:
  security:
    jwtSecret: aa713c1f-8025-4ce4-bfe8-0a8ea6110eea
    jwtExpirationMs: 360 000 000
    jwtRefreshExpirationMs: 60000000
    nova-senha: teste123
    url-cors: http://localhost:4200